import TechPage, { TechData } from "../../components/TechPage";

const data: TechData = {
  slug: "battery-storage",
  title: "Home Battery Storage",
  tagline: "Store your solar energy and use it when you need it most — at night, during peak hours, and in a power cut.",
  icon: "🔋",
  metaDesc: "UK guide to home battery storage — costs, savings, how it works with solar PV, best systems and available incentives.",
  intro: "Home battery storage systems allow you to store excess electricity generated by your solar panels — or cheap off-peak grid electricity — and use it when energy prices are highest or when the sun isn't shining. A typical home battery stores between 5–15kWh of energy. When paired with solar PV, a battery can increase your self-consumption from around 30–40% to 70–90%, dramatically reducing your reliance on the grid. Modern systems can also provide backup power during outages and participate in grid services to earn additional income.",
  howItWorks: [
    { step: "Charge from Solar", desc: "When your solar panels generate more electricity than you're using, the surplus charges the battery instead of being exported." },
    { step: "Charge from Grid (off-peak)", desc: "Smart batteries can also charge overnight using cheap off-peak tariff electricity (e.g. Octopus Go at 7–8p/kWh)." },
    { step: "Discharge When Needed", desc: "In the evening or on cloudy days, the battery discharges to power your home — avoiding expensive peak-rate grid electricity." },
    { step: "Smart Management", desc: "Modern systems use apps and AI to optimise charging and discharging based on weather forecasts, energy prices and your usage patterns." },
  ],
  benefits: [
    "Increases solar self-consumption from ~35% to 70–90%",
    "Reduces evening grid electricity costs significantly",
    "Charge cheaply overnight on off-peak tariffs",
    "Provides backup power in grid outages (some models)",
    "Can earn money through grid services (Virtual Power Plant programmes)",
    "Smart app control and monitoring",
    "Silent and compact — fits in utility room or garage",
    "10-year warranties standard on leading brands",
  ],
  drawbacks: [
    "Significant upfront cost",
    "Best value when paired with solar PV",
    "Battery degrades over time (typically 20–30% capacity loss over 10 years)",
    "Limited value without time-of-use electricity tariff",
    "Not all systems provide power outage backup",
    "Installation requires a qualified electrician",
  ],
  costs: [
    { item: "5–6kWh battery system", range: "£2,500 – £4,000", note: "Suitable for smaller homes or lower solar output" },
    { item: "9–10kWh battery system", range: "£4,000 – £6,500", note: "Most popular for 3–4 bed homes with 4kWp solar" },
    { item: "13–15kWh battery system", range: "£6,000 – £9,000", note: "High usage homes or larger solar arrays" },
    { item: "Installation (if standalone)", range: "£500 – £1,000", note: "Lower if installed alongside solar" },
  ],
  savings: [
    { item: "Additional saving vs solar-only", value: "£300–£600/yr", note: "By avoiding peak-rate grid electricity" },
    { item: "Overnight cheap tariff arbitrage", value: "£200–£400/yr", note: "Based on Octopus Go + peak rate comparison" },
    { item: "Grid services income (VPP)", value: "£100–£300/yr", note: "Varies by provider and participation" },
    { item: "Total with solar + battery", value: "£900–£1,500/yr", note: "Combined annual saving estimate" },
  ],
  suitability: [
    { label: "Homes with solar PV", suitable: true, note: "Ideal pairing — maximises self-consumption" },
    { label: "Homes on time-of-use tariffs", suitable: true, note: "Essential for maximising battery value" },
    { label: "Homes without solar PV", suitable: true, note: "Still valuable for tariff arbitrage" },
    { label: "Properties with EV chargers", suitable: true, note: "Charge car cheaply overnight via battery" },
    { label: "Homes needing outage protection", suitable: true, note: "Select a model with backup mode" },
    { label: "Flats without solar", suitable: false, note: "Limited benefit without solar or flexible tariff" },
  ],
  grants: [
    { name: "0% VAT (with solar PV)", value: "0% VAT", desc: "Battery storage installed alongside solar panels benefits from 0% VAT. Standalone battery installations may attract 20% VAT." },
    { name: "ECO4 / GBIS", value: "Varies", desc: "Some funded schemes include battery storage as part of wider energy efficiency packages for eligible households." },
    { name: "Smart Export Guarantee", value: "4–15p/kWh", desc: "Batteries can be configured to export surplus at peak times, maximising SEG income from your solar system." },
    { name: "Virtual Power Plant schemes", value: "£100–£300/yr", desc: "Companies like Octopus, Tesla and others pay battery owners to participate in grid balancing services." },
  ],
  faqs: [
    { q: "What size battery do I need?", a: "A good rule of thumb is to match your battery capacity to your evening/overnight electricity usage. Most 3-4 bed homes use 5–10kWh between sunset and sunrise, making a 9–10kWh battery a popular choice." },
    { q: "Can a battery power my home in a blackout?", a: "Some batteries (such as Tesla Powerwall 2 or GivEnergy AIO) offer 'backup' or 'islanding' mode that can keep essential circuits running during a power cut. Not all systems offer this — check before purchasing." },
    { q: "Which battery brands are best?", a: "Popular UK choices include Tesla Powerwall, GivEnergy, SolarEdge, Sungrow and Victron. The best choice depends on your existing solar inverter, budget and whether you need backup capability." },
    { q: "How long will the battery last?", a: "Most leading brands guarantee 70% capacity retention after 10 years. Real-world lifespans of 12–15 years are common with proper management." },
    { q: "Do I need planning permission for a battery?", a: "No. Home battery storage systems are permitted development and do not require planning permission." },
    { q: "Can I add a battery to my existing solar system?", a: "Yes, in most cases. AC-coupled batteries can be added to virtually any existing solar system. DC-coupled options may require inverter replacement but offer greater efficiency." },
  ],
  related: [
    { title: "Solar PV", slug: "solar-pv", icon: "☀️" },
    { title: "EV Charger", slug: "ev-charger", icon: "⚡" },
    { title: "Air Source Heat Pump", slug: "air-source-heat-pump", icon: "🌡️" },
    { title: "Solar Thermal", slug: "solar-thermal", icon: "🌞" },
  ],
};

export default function BatteryStorage() {
  return <TechPage data={data} />;
}
